name: Validate

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to validate
        required: false
        type: string
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install pytest asyncssh homeassistant voluptuous
      - run: pytest tests/

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}
      - uses: hacs/action@main
        with:
          category: integration
